### ISSUE TITLE
Fix dead lock when updating wallet.dat

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#655]
The problems is in Berkeley DB level. What I guess is the previous write to `wallet.db` put a lock in the database and did not remove it.

Here is the stack trace:

```
#0  0x00007f7a32c76415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f7a336361d9 in __db_pthread_mutex_lock (env=env@entry=0x55a62442a418, mutex=mutex@entry=372) at ../dist/../mutex/mut_pthread.c:318
#2  0x00007f7a3363552e in __db_tas_mutex_lock_int (env=0x55a62442a418, mutex=372, nowait=0) at ../dist/../mutex/mut_tas.c:218
#3  0x00007f7a336cb3a9 in __lock_get_internal (lt=0x7f7a14004b38, sh_locker=0x7f7a14cb7230, flags=0, obj=0x7f79e01076b8, lock_mode=DB_LOCK_WRITE, timeout=0, lock=0x7f79e6ffac20) at ../dist/../lock/lock.c:953
#4  0x00007f7a336cbd3c in __lock_get (env=env@entry=0x55a62442a418, locker=0x7f7a14cb7230, flags=<optimized out>, obj=obj@entry=0x7f79e01076b8, lock_mode=<optimized out>, lock=lock@entry=0x7f79e6ffac20) at ../dist/../lock/lock.c:459
#5  0x00007f7a33704aee in __db_lget (dbc=dbc@entry=0x7f79e01075d8, action=<optimized out>, action@entry=0, pgno=<optimized out>, mode=<optimized out>, mode@entry=DB_LOCK_WRITE, lkflags=<optimized out>, lockp=lockp@entry=0x7f79e6ffac20)
    at ../dist/../db/db_meta.c:1203
#6  0x00007f7a33655132 in __bam_search (dbc=dbc@entry=0x7f79e01075d8, root_pgno=root_pgno@entry=3, key=key@entry=0x7f79e6ffb260, flags=12802, slevel=slevel@entry=1, recnop=recnop@entry=0x0, exactp=0x7f79e6ffad7c) at ../dist/../btree/bt_search.c:702
#7  0x00007f7a3363f514 in __bamc_search (dbc=dbc@entry=0x7f79e01075d8, root_pgno=3, key=key@entry=0x7f79e6ffb260, flags=<optimized out>, exactp=exactp@entry=0x7f79e6ffad7c) at ../dist/../btree/bt_cursor.c:2785
#8  0x00007f7a3364390d in __bamc_put (dbc=0x7f79e01075d8, key=0x7f79e6ffb260, data=0x7f79e6ffb2c0, flags=14, pgnop=0x7f79e6ffadf4) at ../dist/../btree/bt_cursor.c:2130
#9  0x00007f7a336f46da in __dbc_iput (dbc=0x7f79e01075d8, key=0x7f79e6ffb260, data=0x7f79e6ffb2c0, flags=14) at ../dist/../db/db_cam.c:2103
#10 0x00007f7a336f6106 in __dbc_put (dbc=<optimized out>, key=key@entry=0x7f79e6ffb260, data=data@entry=0x7f79e6ffb2c0, flags=14, flags@entry=0) at ../dist/../db/db_cam.c:2016
#11 0x00007f7a336e84e2 in __db_put (dbp=dbp@entry=0x7f79e0085e48, ip=<optimized out>, txn=0x7f79e003f808, key=key@entry=0x7f79e6ffb260, data=data@entry=0x7f79e6ffb2c0, flags=flags@entry=0) at ../dist/../db/db_am.c:477
#12 0x00007f7a3370290c in __db_put_pp (dbp=0x7f79e0085e48, txn=<optimized out>, key=0x7f79e6ffb260, data=0x7f79e6ffb2c0, flags=<optimized out>) at ../dist/../db/db_iface.c:1579
#13 0x00007f7a33628e91 in Db::put (this=0x7f79e01cbc90, txnid=<optimized out>, key=<optimized out>, value=<optimized out>, flags=<optimized out>) at ./db_cxx.h:1002
#14 0x000055a622d82446 in CDB::Write<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long> (this=0x7f79e00e2d90, key="orderposnext", value=@0x7f79e6ffb310: 526, fOverwrite=true) at ./wallet/db.h:170
#15 0x000055a622d72574 in CWalletDB::WriteOrderPosNext (this=0x7f79e00e2d90, nOrderPosNext=526) at wallet/walletdb.cpp:134
#16 0x000055a622cebc54 in CWallet::IncOrderPosNext (this=0x7f7a14cc7570, pwalletdb=0x7f79e00e2d90) at wallet/wallet.cpp:735
#17 0x000055a622cec9eb in CWallet::AddToWallet (this=0x7f7a14cc7570, wtxIn=..., fFromLoadWallet=false, pwalletdb=0x7f79e00e2d90) at wallet/wallet.cpp:852
#18 0x000055a622d029f4 in CWallet::CommitTransaction (this=0x7f7a14cc7570, tx=...) at wallet/wallet.cpp:3775
#19 0x000055a622d1985d in CWallet::CommitSigmaTransaction (this=0x7f7a14cc7570, wtxNew=..., selectedCoins=std::vector of length 1, capacity 1 = {...}, changes=std::vector of length 15, capacity 15 = {...}) at wallet/wallet.cpp:6934
#20 0x000055a622a81899 in exodus::WalletTxBuilder (senderAddress="", receiverAddress="TGdSfQ7N2UBPyqH3kADiyFXEHFkDiwNdxH", redemptionAddress="", referenceAmount=0, data=std::vector of length 1191, capacity 1191 = {...}, txid=..., rawHex="", commit=true,
    inputMode=exodus::InputMode::SIGMA) at exodus/exodus.cpp:2519
#21 0x000055a622b82acb in exodus_sendspend (params=..., fHelp=false) at exodus/rpctx.cpp:1671
#22 0x000055a622984190 in CRPCTable::execute (this=0x55a623e2f000 <tableRPC>, strMethod="exodus_sendspend", params=...) at rpc/server.cpp:452
#23 0x000055a6225bcb41 in RPCExecutor::request (this=0x55a624caaf10, command=...) at qt/rpcconsole.cpp:215
#24 0x000055a6225bc2ec in RPCExecutor::qt_static_metacall (_o=0x55a624caaf10, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x55a625b544a0) at qt/rpcconsole.moc:81
#25 0x00007f7a33d8244a in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#26 0x00007f7a347a54d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#27 0x00007f7a347aea21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#28 0x00007f7a33d559c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#29 0x00007f7a33d58739 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#30 0x00007f7a33dae3a4 in ?? () from /usr/lib/libQt5Core.so.5
#31 0x00007f7a31e6fcf4 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0x00007f7a31e71b11 in ?? () from /usr/lib/libglib-2.0.so.0
#33 0x00007f7a31e71b51 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0x00007f7a33dad9a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007f7a33d545ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#36 0x00007f7a33b872f5 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#37 0x00007f7a33b88520 in ?? () from /usr/lib/libQt5Core.so.5
#38 0x00007f7a32c7057f in start_thread () from /usr/lib/libpthread.so.0
#39 0x00007f7a32b9e0e3 in clone () from /usr/lib/libc.so.6
```

**Comment by ultimaweapon** [comment]
After a full day investigation still no luck. So I will come back later.

**Comment by ultimaweapon** [comment]
@thebevrishot just found out we forgot to delete a database cursor when we done with it.
